name = "pong_erlang"
version = "1.0.0"
description = "PoC program for a game in gleam utilizing the erlang target"
licences = ["GPL-3.0-only"]
repository = { type = "github", user = "Faeq-F", repo = "https://github.com/Faeq-F/Zarlasht" }

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
lustre = ">= 4.5.0 and < 5.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"
gleam_otp = ">= 0.14.1 and < 1.0.0"
wisp = ">= 1.2.0 and < 2.0.0"
radish = ">= 0.15.0 and < 1.0.0"
glenvy = ">= 1.1.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.1.0 and < 2.0.0"
lucide_lustre = ">= 2.0.0 and < 3.0.0"
