name = "screen_designs"
version = "1.0.0"
description = "Screen Designs for Zarlasht"
licences = ["GPL-3.0-only"]
repository = { type = "github", user = "Faeq-F", repo = "https://github.com/Faeq-F/Zarlasht" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.3.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
