name = "tictactoe_javascript"
version = "1.0.0"
description = "PoC program for a board game in gleam utilizing the javascript target"
licences = ["GPL-3.0-only"]
repository = { type = "github", user = "Faeq-F", repo = "https://github.com/Faeq-F/Zarlasht" }

target = "javascript"
[javascript]
runtime = "deno"

[javascript.deno]
allow_read = true
allow_net = true
allow_run = ["gleam", "javascript"]
allow_env = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glen = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_javascript = ">= 0.11.0 and < 1.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
lustre = ">= 4.5.0 and < 5.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.1.0 and < 2.0.0"
