name = "online_chat_javascript"
version = "1.0.0"

target = "javascript"
[javascript]
runtime = "deno"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glen = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_javascript = ">= 0.11.0 and < 1.0.0"
lustre = ">= 4.5.0 and < 5.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_fetch = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.1.0 and < 2.0.0"

[javascript.deno]
allow_read = ["./"]
allow_net = ["deno.land"]
allow_run = ["gleam"]
