name = "automated_browser_tests"
version = "1.0.0"
description = "Project for automated browser tests (erlang target); tests are for the PoC program in the parent directory"
licences = ["GPL-3.0-only"]
# repository = { type = "github", user = "", repo = "" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glacier = ">= 1.1.0 and < 2.0.0"
chrobot = ">= 3.0.2 and < 4.0.0"
repeatedly = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
